### ISSUE TITLE
generateEthBlock failed

### ISSUE THREAD

**Issue by cherideal** [oasisprotocol/oasis-web3-gateway#91]
```
{"caller":"backend.go:124","level":"info","module":"indexer","msg":"indexed block","round":857,"ts":"2021-12-04T01:26:07.949906418Z"}
{"caller":"utils.go:231","index":0,"level":"error","module":"indexer","msg":"Failed to unmarshal event value","ts":"2021-12-04T01:26:07.966591268Z"}
{"caller":"backend.go:120","err":"cbor: cannot unmarshal map into Go value of type []*indexer.Log","level":"error","module":"indexer","msg":"generateEthBlock failed","ts":"2021-12-04T01:26:07.966637861Z"}
{"caller":"indexer.go:149","err":"index block failed","level":"warn","module":"gateway/indexer","msg":"failed to index block","round":858,"runtime_id":"00000000000000000000000000000000000000000000000072c8215e60d5bca7","ts":"2021-12-04T01:26:12.966832764Z"}
{"caller":"utils.go:231","index":0,"level":"error","module":"indexer","msg":"Failed to unmarshal event value","ts":"2021-12-04T01:26:12.983382784Z"}
{"caller":"backend.go:120","err":"cbor: cannot unmarshal map into Go value of type []*indexer.Log","level":"error","module":"indexer","msg":"generateEthBlock failed","ts":"2021-12-04T01:26:12.983442699Z"}
```

**Comment by kostko** [comment]
This is fixed in #90 and is related to the recent SDK upgrade.

**Comment by ptrus** [comment]
Try again with latest master version, should be fixed

**Comment by cherideal** [comment]
The question still exists, do I need to recompile emerald-paratime or just recompile the gateway?

**Comment by kostko** [comment]
Just the gateway.

**Comment by cherideal** [comment]
I recompile the gateway and it still here. Please confirm it again.

**Comment by kostko** [comment]
What error do you get with the new version of the gateway, can you post the new logs?

**Comment by ptrus** [comment]
Maybe the logged error message was confusing (fix in https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/92) as previously the error was still logged, however the indexer did successfully index the logs.

**Comment by kostko** [comment]
Looks like there's still an issue with incorrect error being checked, should be fixed in #94.
